### PR TITLE
Pull request hip

### PR DESCRIPTION
**Pull request by sunway513**
Hello Ekondis,
This pull request is on behalf of AMD HIP team. 
In this request, we have included:
1. mixbench-hip and mixbench-hip-ro, tested on both NV machine with Titan X and AMD machine with FIJI NANO.
2. Modified Makefile to detect if HIP is available on system and generate HIP binaries accordingly.
3. Add performance data of mixbench-hip and mixbench-hip-ro on TITAN X and FIJI NANO.
4. Minor fix of incorrect file modes.

Please kindly review it and let us know any questions or suggestions on this pull request.

Regards,
Peng

### CODE REVIEW

**Comment by ekondis** [comment]
Dear Peng,
Thank you for your contribution. I just removed GTX_TITANX.txt from the project's folder as it didn't fit there.

In case I have any questions I'll let you know.

Thank you.

**Comment by sunway513** [comment]
Dear Ekondis,
Thanks so much, we are very glad to see this pull request has been accepted and merged!

Please let us know if you have any questions about it and any collaboration opportunities in the future :-)

Regards,
Peng

**Comment by ekondis** [comment]
Dear Peng,
You're welcome. I'll hopefully be able to test the HIP implementation in the near future as currently I don't have access to HIP supported hardware.

Btw, HIP API calls in the source code seem to be equivalent to the CUDA calls in one to one correspondence. Even the kernel code seem identical. So, is HIP a CUDA API implementation? A path to moving projects to a vendor neutral framework?

I'm certainly positive in collaboration. How could this be done?

Regards,
Elias

**Comment by sunway513** [comment]
Hello Elias,
Thanks so much for the promoting response.

You are right, HIP is an open sourced project that moving CUDA-based
projects to a vendor-neutral framework.
By porting applications with HIP, we could execute the project on both NV
and AMD platforms.
On NV platform, HIP tool will simply translation the source code to call
CUDA compilers, runtime and libraries for compilation and execution.
While on the AMD platform, HCC will compile the application, and the HIP
runtime translates the HIP APIs to ROCR&ROCK runtime libraries and HCC
libraries.

We could achieve very compatible performance results so far by comparing
the AMD FIJI NANO with the Titan X on a various of benchmarks including
"mixbench". We are actively contributing to the HIP project for better
performance, compatibilities and the ease of porting CUDA-enabled projects.

For now, you could refer to the GPU Open blog
http://gpuopen.com/professional-compute/ regarding how to set up HIP
environment on CUDA platforms and test on the benchmarks, and later move to
an AMD platform.
Please let me know if anything I could help with :-)

On Sat, Mar 19, 2016 at 3:56 AM, Elias notifications@github.com wrote:

> Dear Peng,
> You're welcome. I'll hopefully be able to test the HIP implementation in
> the near future as currently I don't have access to HIP supported hardware.
> 
> Btw, HIP API calls in the source code seem to be equivalent to the CUDA
> calls in one to one correspondence. Even the kernel code seem identical.
> So, is HIP a CUDA API implementation? A path to moving projects to a vendor
> neutral framework?
> 
> I'm certainly positive in collaboration. How could this be done?
> 
> Regards,
> Elias
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ekondis/mixbench/pull/1#issuecomment-198670148

## 

Best Regards,
Peng

**Pull request merged**
